---
title: "Post-processing"
output: html_document
---

```{r}

library(pacman)
p_load(dplyr, ggplot2, papaja)

df <- read.csv("file1.csv")

df$entropyBinned <- cut(df$entropy, breaks=c(0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1))

aggDF <- aggregate(df, correct ~ nStates + entropyBinned + corpusSize + trueK, FUN = mean)

df$nStates = as.factor(df$nStates)
df$trueK = as.factor(df$trueK)

ggplot(df, aes(x = nStates, y = correct, group = trueK, color = trueK, fill = trueK))+
  stat_summary(geom = 'line', position = 'identity', fun = 'mean')+
  stat_summary(geom = 'point', position = 'identity', fun = 'mean')+
  stat_summary(geom="errorbar", fun.data=mean_cl_normal)+
  scale_y_continuous(limits = c(0,1))+
  scale_color_manual(values = c('pink', 'lightblue','mediumpurple1', 'palegreen'))+
  theme_apa()





bests <- fishColResults %>% 
  group_by(species) %>%
  slice_max(log_likelihood)


```

Best Ks
```{r}

# df <- read.csv("birdResultsFull.csv")
# df <- read.csv("birdResultsCropped.csv")
df <- read.csv("fishResultsCollapsed.csv")

maxs <- df %>%
  group_by(species, sim) %>%
  slice_max(log_likelihood, n = 1, with_ties = T) %>%
  ungroup()

result <- maxs %>%
  count(species, k, name = "count") %>%
  group_by(species) %>%
  slice_max(count, n = 1, with_ties = F) %>%
  ungroup()

result #most occurring best k by species

#full results
# maxs %>%
#   count(species, k, sort = TRUE)




```

